# Generated by Django 6.0 on 2026-01-12 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_dewey', models.CharField(help_text='Ej: 800, Literatura', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('cutter', models.CharField(help_text='Código Cutter del Autor/titulo', max_length=50)),
                ('descripcion', models.TextField(verbose_name='Sinopsis')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='libros/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autores', models.ManyToManyField(related_name='libros', to='catalog.autor')),
                ('generos', models.ManyToManyField(related_name='libros', to='catalog.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(choices=[('ESTADAL', 'Estante Estadal'), ('INFANTIL', 'Estante Infantil'), ('GENERAL', 'Estante General'), ('REFERENCIA', 'Sala de Referencia')], max_length=50)),
                ('estante', models.CharField(help_text='Ej: Estante 1', max_length=100)),
                ('nivel', models.CharField(help_text='Ej: Nivel Superior, Fila 2', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
                'unique_together': {('sala', 'estante', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio_publicacion', models.IntegerField(verbose_name='Año de Publicación')),
                ('codigo_inventario', models.CharField(help_text='Código de etiquetas', max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('PERDIDO', 'Perdido')], default='DISPONIBLE', max_length=20)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.editorial')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='catalog.libro')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejemplares', to='catalog.ubicacion')),
            ],
        ),
    ]
