# Generated by Django 6.0 on 2026-01-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='codigo_inventario',
        ),
    ]
