# Generated by Django 6.0 on 2026-01-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_ejemplar_codigo_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='sala',
            field=models.CharField(choices=[('ESTADAL', 'Sala Estadal'), ('INFANTIL', 'Sala Infantil'), ('GENERAL', 'Sala General'), ('REFERENCIA', 'Sala de Referencia')], max_length=50),
        ),
    ]
