# Generated by Django 6.0 on 2026-01-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_ubicacion_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='codigo_inventario',
            field=models.CharField(default='1', max_length=50, unique=True, verbose_name='Código de Inventario'),
        ),
    ]
