# Generated by Django 6.0 on 2026-01-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_ejemplar_codigo_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='codigo_inventario',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Código de Inventario'),
        ),
    ]
