# Generated by Django 6.0 on 2026-01-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='enlace',
            field=models.CharField(blank=True, help_text='Link de acción (ej. descargar pdf)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('INFO', 'Información General'), ('APROBADO', 'Solicitud Aprobada'), ('RECHAZADO', 'Solicitud Rechazada'), ('ALERTA', 'Alerta / Vencimiento')], default='INFO', max_length=20),
        ),
    ]
