# Generated by Django 6.0 on 2026-01-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
